title: Christian Dewein
email: fabrik42@gmail.com
baseurl: ""
url: "https://christiandewein.com"

description: >
  Hi! My name is Christian Dewein,
  a software developer living in Frankfurt, Germany.

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  projects:
    sort_by: order

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      image: "/assets/social-link-image.jpg"

exclude:
  - README.org
  - slides_backup

# Social / SEO settings

logo: "/assets/social-link-logo.jpg"

google_site_verification: "ok3_egP8JYWNjujovfiEWeCPFMnI9c49PYcBlAREkr4"

author:
  name: Christian Dewein
  twitter: fabrik42
  url: https://christiandewein.com
  picture: /assets/social-link-author.jpg

social:
  name: Christian Dewein
  links:
    - https://twitter.com/fabrik42
    - https://mastodon.social/@fabrik42
    - https://www.linkedin.com/in/christian-baeuerlein
    - https://github.com/fabrik42
