#+BEGIN_EXPORT html
---
title: Me, right now
description: What I am doing right now in case we didn't meet for a while and you want to catch up.
layout: post
permalink: /now
---
#+END_EXPORT

* {{ page.title }}
** New name!
I got married and therefore changed my family name from /Christian Bäuerlein/ to /Christian Dewein/!

I always liked my old name as well, but getting rid of the Umlaut is - even in 2024 - very convenient!
** Living in Frankfurt am Main
I live in Frankfurt am Main and still enjoy living in this city!
** Working at ioki
I am the CTO of the ioki GmbH in Frankfurt - a 100% subsidary of Deutsche Bahn.
Since 2017 I am part of this company and I am very proud of it.
** Travelling
Over the last years, I did quite some travelling. I like to explore nature and experience wildlife. Most notably, I travelled to Costa Rica, Namibia and the west coast of North America since the end of the pandemic.
** Meetups
I love being part of Frankfurt's meetup scene. I organize a couple meetups myself and visit even more. I also like to serve as a host for other meetups at my company.

Most notably I organize the [[./mechanicon][Mechanicon - Europe's biggest mechanical keyboard conference]].
